spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/MojiStep
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: false
    locations: classpath:db/migration

app:
  jwt:
    # Must be Base64
    secret: "lHkUk4dNXCHFT57+euLVvdYnV+m+3hL/YnCJ7HlKjws="
    issuer: "mojistep-api"

    # ISO-8601 durations
    access-token-ttl: "PT1H"      # 1 hour
    refresh-token-ttl: "P14D"     # 14 days

logging:
  file:
    name: logs/app.log
  level:
    root: INFO